### ISSUE TITLE
Map picks in API

### ISSUE THREAD

**Issue by robinrossow** [Astraeus-/heroeslounge-api#1]
Hey, I'd like to access the specific map picks for each team but I can't seem to find anything like that in the endpoints. They are shown on the website though so I'm wondering if there actually is an endpoint or if I'm just blind.

**Comment by Astraeus-** [comment]
Hey, thanks for pointing this out! I haven't got around to adding some of the newer routes. I'll hopefully be able to add these somewhere this weekend.

**Comment by Astraeus-** [comment]
Fixed in commit 39d159fd41420f8fbfe537ca2c19196ea7632262 which is part of the latest release [2.5.0](https://github.com/Astraeus-/heroeslounge-api/releases/tag/2.5.0) available on npm.
